# This is a small antora playbook for local testing
# It is based on antora-playbook.yml in repo dfinity-docs-playbook
# but stripped down to only build the language guide
#
# Build with
#
#    antora antora-playbook.yml
#
# and then edit open build/site/motoko/language-guide/motoko.html
site:
    title: Motoko documentation
    #url: https://sdk.dfinity.org
    start_page: docs::index.adoc
content:
    sources:
    - url: ..
      branches: HEAD
      start_path: doc
    # TODO: Pull in Motoko base
    #- url: ../../motoko-base
    #  branches: 'doc-pages'
    - url: https://github.com/icpleague/docs-cn.git
      branches: HEAD
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
      edit_url: false
ui:
  bundle:
    # local copy of https://github.com/dfinity/antora-sdk/raw/master/build/ui-bundle.zip
    url: ./test-ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    proglang: Motoko
    company-id: DFINITY
    toc: ~
    platform: Internet Computer platform
    IC: Internet Computer
    #sdk-short-name: DFINITY Canister SDK
    sdk-long-name: DFINITY Canister Software Development Kit (SDK)
    page-moc-version: 0.5.5
    page-moc-base-tag: dfx-0.6.18
