name: MakeDoc CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: install dependencies
        run: |
          sudo apt install pandoc -y  
      - name: install dependencies
        run: |
          sudo apt install make -y
      - name: Build
        run: |
          cd doc
          make
